# Generated by Django 3.2.9 on 2021-11-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('Uname', models.CharField(default='unnamed', max_length=50, verbose_name='用户名')),
                ('Passwd', models.CharField(default='password-not-set', max_length=25, verbose_name='密码')),
                ('isEDIT', models.IntegerField(default=0, verbose_name='是否为编辑')),
                ('header', models.ImageField(default='/static/img/default.png', upload_to='userHeader', verbose_name='用户头像')),
                ('AgeRange', models.IntegerField(verbose_name='年龄段')),
                ('rank', models.IntegerField(verbose_name='用户等级')),
                ('public', models.IntegerField(verbose_name='是否仅关注后可见')),
                ('public_Ftopic', models.IntegerField(verbose_name='是否展示关注的话题')),
                ('public_Fuser', models.IntegerField(verbose_name='是否展示关注的人')),
                ('public_comments', models.IntegerField(verbose_name='是否展示发表的评论')),
                ('public_events', models.IntegerField(verbose_name='是否发表的报料')),
                ('public_topics', models.IntegerField(verbose_name='是否展示发表的话题')),
                ('introduction', models.TextField(verbose_name='个人介绍')),
                ('wechatID', models.CharField(default='WeiChatID-not-set', max_length=30, verbose_name='微信ID')),
                ('EXP', models.IntegerField(verbose_name='经验值')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
    ]
