# Generated by Django 3.2.9 on 2021-11-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False, verbose_name='活动ID')),
                ('Title', models.TextField(verbose_name='活动标题')),
                ('Introduction', models.TextField(verbose_name='活动介绍')),
                ('isEND', models.BooleanField(default=False, verbose_name='正在进行/结束')),
                ('reward', models.IntegerField(default=0, verbose_name='活动EXP奖励')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='activity_comments',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('AID', models.IntegerField(verbose_name='所属活动ID')),
                ('value', models.TextField(verbose_name='评论内容')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('star', models.IntegerField(verbose_name='点赞数')),
                ('tip_off', models.IntegerField(verbose_name='举报数')),
                ('status', models.BooleanField(default=True, verbose_name='显示/下架锁定')),
            ],
            options={
                'verbose_name': '活动评论',
                'verbose_name_plural': '活动评论',
                'db_table': 'activity_comments',
            },
        ),
        migrations.CreateModel(
            name='activity_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField(verbose_name='活动ID')),
                ('item', models.CharField(max_length=255, verbose_name='条目名')),
                ('counts', models.IntegerField(verbose_name='计数')),
            ],
            options={
                'verbose_name': '活动投票',
                'verbose_name_plural': '活动投票',
                'db_table': 'activity_vote',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='目标用户ID')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('value', models.CharField(max_length=255, verbose_name='标题')),
                ('postTime', models.DateTimeField(verbose_name='推送时间')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='topic_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.IntegerField(verbose_name='话题ID')),
                ('item', models.CharField(max_length=255, verbose_name='条目名')),
                ('counts', models.IntegerField(verbose_name='计数')),
            ],
            options={
                'verbose_name': '话题投票',
                'verbose_name_plural': '话题投票',
                'db_table': 'topic_vote',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='Tag',
            field=models.CharField(default='', max_length=255, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='userfollow_topic',
            name='lastVisitTime',
            field=models.IntegerField(default=0, verbose_name='最后访问时间戳'),
        ),
        migrations.AddField(
            model_name='userfollow_user',
            name='lastVisitTime',
            field=models.IntegerField(default=0, verbose_name='最后访问时间戳'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.IntegerField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.IntegerField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='revelation',
            name='time',
            field=models.IntegerField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lastUpDateTime',
            field=models.IntegerField(verbose_name='话题最后更新时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='time',
            field=models.IntegerField(verbose_name='发布时间'),
        ),
    ]
