# Generated by Django 3.2.9 on 2021-11-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacy',
            name='public',
            field=models.BooleanField(default=False, verbose_name='是否仅关注后可见'),
        ),
        migrations.AlterField(
            model_name='userprivacy',
            name='public_events',
            field=models.BooleanField(default=True, verbose_name='是否展示发表的报料'),
        ),
    ]
