# Generated by Django 3.2.9 on 2021-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('TID', models.IntegerField(verbose_name='所属话题ID')),
                ('value', models.TextField(verbose_name='评论内容')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('star', models.IntegerField(verbose_name='点赞数')),
                ('tip_off', models.IntegerField(verbose_name='举报数')),
                ('status', models.BooleanField(default=True, verbose_name='显示/下架锁定')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField(verbose_name='所属话题ID')),
                ('UID', models.IntegerField(verbose_name='发布者ID')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('statement', models.TextField(verbose_name='导语')),
                ('star', models.IntegerField(verbose_name='点赞数')),
                ('tip_off', models.IntegerField(verbose_name='举报数')),
                ('status', models.BooleanField(default=True, verbose_name='显示/下架锁定')),
                ('isPostByEditor', models.BooleanField(default=False, verbose_name='是否是编辑发布的内容')),
                ('url', models.CharField(max_length=255, verbose_name='来源URL')),
                ('eventTime', models.DateTimeField(verbose_name='事件的时间节点')),
            ],
            options={
                'verbose_name': '引用',
                'verbose_name_plural': '引用',
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='index_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField(verbose_name='所属话题ID')),
                ('img', models.ImageField(default='/static/img/default.png', upload_to='baoliao', verbose_name='图片url')),
            ],
            options={
                'verbose_name': '首页图',
                'verbose_name_plural': '首页图',
                'db_table': 'index_pic',
            },
        ),
        migrations.CreateModel(
            name='Revelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField(verbose_name='所属话题ID')),
                ('UID', models.IntegerField(verbose_name='发布者ID')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('statement', models.TextField(verbose_name='导语')),
                ('star', models.IntegerField(default=0, verbose_name='点赞数')),
                ('tip_off', models.IntegerField(default=0, verbose_name='举报数')),
                ('status', models.BooleanField(default=True, verbose_name='显示/下架锁定')),
                ('isPostByEditor', models.BooleanField(default=False, verbose_name='是否是编辑发布的内容')),
                ('text', models.TextField(verbose_name='爆料内容')),
                ('eventTime', models.DateTimeField(verbose_name='事件的时间节点')),
            ],
            options={
                'verbose_name': '爆料',
                'verbose_name_plural': '爆料',
                'db_table': 'Revelation',
            },
        ),
        migrations.CreateModel(
            name='Revelation_Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.IntegerField(verbose_name='所属报料ID')),
                ('img', models.ImageField(default='/static/img/default.png', upload_to='baoliao', verbose_name='爆料图片')),
            ],
            options={
                'verbose_name': '爆料图片',
                'verbose_name_plural': '爆料图片',
                'db_table': 'Revelation_Pic',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='发布者ID')),
                ('category', models.IntegerField(verbose_name='话题所属类别')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('statement', models.TextField(verbose_name='导语')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('star', models.IntegerField(verbose_name='点赞数')),
                ('tip_off', models.IntegerField(verbose_name='举报数')),
                ('status', models.BooleanField(default=True, verbose_name='显示/下架锁定')),
                ('isPostByEditor', models.BooleanField(default=False, verbose_name='是否是编辑发布的内容')),
                ('lastUpDateTime', models.DateTimeField(verbose_name='话题最后更新时间')),
                ('Fcounts', models.IntegerField(default=0, verbose_name='关注数')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='userFollow_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('FTID', models.IntegerField(verbose_name='被关注人的ID')),
                ('AgeRange', models.IntegerField(default='0', verbose_name='年龄段')),
            ],
            options={
                'verbose_name': '用户关注的话题',
                'verbose_name_plural': '用户关注的话题',
                'db_table': 'userFollow_topic',
            },
        ),
        migrations.CreateModel(
            name='userFollow_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('FUID', models.IntegerField(verbose_name='被关注人的ID')),
                ('FUname', models.CharField(default='unnamed', max_length=25, verbose_name='被关注人的用户名')),
                ('AgeRange', models.IntegerField(default='0', verbose_name='年龄段')),
            ],
            options={
                'verbose_name': '用户关注的博主',
                'verbose_name_plural': '用户关注的博主',
                'db_table': 'userFollow_user',
            },
        ),
        migrations.CreateModel(
            name='userInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
                ('field', models.IntegerField(verbose_name='兴趣领域')),
            ],
            options={
                'verbose_name': '用户兴趣',
                'verbose_name_plural': '用户兴趣',
                'db_table': 'UserInterests',
            },
        ),
        migrations.CreateModel(
            name='userPrivacy',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('public', models.BooleanField(default=True, verbose_name='是否仅关注后可见')),
                ('public_Ftopic', models.BooleanField(default=True, verbose_name='是否展示关注的话题')),
                ('public_Fuser', models.BooleanField(default=True, verbose_name='是否展示关注的人')),
                ('public_comments', models.BooleanField(default=True, verbose_name='是否展示发表的评论')),
                ('public_events', models.BooleanField(default=True, verbose_name='是否发表的报料')),
                ('public_topics', models.BooleanField(default=True, verbose_name='是否展示发表的话题')),
            ],
            options={
                'verbose_name': '用户空间权限',
                'verbose_name_plural': '用户空间权限',
                'db_table': 'userPrivacy',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='public',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_Ftopic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_Fuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_topics',
        ),
        migrations.AddField(
            model_name='user',
            name='Fcounts',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Uname',
            field=models.CharField(default='unnamed', max_length=25, verbose_name='用户名'),
        ),
    ]
