# Generated by Django 3.2.9 on 2021-12-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20211126_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='PID',
            new_name='TID',
        ),
    ]
