# Generated by Django 3.2.9 on 2021-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rename_pid_events_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ifPassedExam',
            field=models.BooleanField(default=False, verbose_name='是否通过了会员测试'),
        ),
    ]
