# Generated by Django 3.2.9 on 2021-12-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_rename_pid_revelation_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revelation_pic',
            old_name='EID',
            new_name='RID',
        ),
    ]
