# Generated by Django 3.2.9 on 2021-12-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_contributes_pic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='poster',
            field=models.ImageField(default='/static/img/default.png', upload_to='poster', verbose_name='活动海报'),
        ),
    ]
