# Generated by Django 3.2.9 on 2021-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_activity_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='tip_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='对象类型')),
                ('points', models.IntegerField(verbose_name='扣分数')),
                ('UID', models.IntegerField(verbose_name='被举报人ID')),
            ],
            options={
                'verbose_name': '举报审核队列',
                'verbose_name_plural': '举报审核队列',
                'db_table': 'tip_off',
            },
        ),
    ]
