# Generated by Django 3.2.9 on 2021-12-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_tip_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip_off',
            name='valueID',
            field=models.IntegerField(default=0, verbose_name='举报对象ID'),
        ),
    ]
