# Generated by Django 3.2.9 on 2021-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_tip_off_valueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='AgeRange_avg',
            field=models.IntegerField(default=0, verbose_name='受欢迎年龄段'),
        ),
    ]
