# Generated by Django 3.2.9 on 2021-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_topic_agerange_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='对象类型')),
                ('UID', models.IntegerField(verbose_name='点赞人ID')),
                ('valueID', models.IntegerField(verbose_name='点赞对象ID')),
            ],
            options={
                'verbose_name': '点赞记录',
                'verbose_name_plural': '点赞记录',
                'db_table': 'Star',
            },
        ),
    ]
