# Generated by Django 3.2.9 on 2021-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_topic_vote_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Uname',
            field=models.CharField(default='', max_length=25, verbose_name='用户名'),
        ),
    ]
