# Generated by Django 3.2.9 on 2021-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_topic_hotpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_contribute',
            name='hotPoints',
            field=models.FloatField(default=0.0, verbose_name='热值'),
        ),
        migrations.AddField(
            model_name='comments',
            name='hotPoints',
            field=models.FloatField(default=0.0, verbose_name='热值'),
        ),
    ]
