# Generated by Django 3.2.9 on 2021-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20211204_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='revelation',
            name='type',
            field=models.IntegerField(default=1, verbose_name='类型'),
        ),
    ]
