# Generated by Django 3.2.9 on 2021-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20211205_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.IntegerField(default=2, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='revelation',
            name='type',
            field=models.IntegerField(default=3, verbose_name='类型'),
        ),
    ]
