# Generated by Django 3.2.9 on 2021-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20211205_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Uname',
        ),
    ]
