# Generated by Django 3.2.9 on 2021-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_remove_comments_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mainPic',
            field=models.ImageField(default='/static/img/default.png', upload_to='topic', verbose_name='话题首图'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(default='/static/img/header_default.png', upload_to='userHeader', verbose_name='用户头像'),
        ),
    ]
