# Generated by Django 3.2.9 on 2021-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20211209_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='typeID',
            field=models.IntegerField(default=-1, verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='star',
            name='valueID',
            field=models.IntegerField(verbose_name='被点赞用户ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='mainPic',
            field=models.ImageField(default='default.png', upload_to='topic', verbose_name='话题首图'),
        ),
    ]
