# Generated by Django 3.2.9 on 2021-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20211212_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='typeID',
            field=models.IntegerField(default=0, verbose_name='对象ID'),
        ),
    ]
