# Generated by Django 3.2.9 on 2021-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_remove_star_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='typeID',
            field=models.IntegerField(default=1, verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='postTime',
            field=models.IntegerField(verbose_name='推送时间'),
        ),
    ]
